version: "3"

services:
    postgres:
        container_name: airflow-db
        env_file:
            - postgres.env
        image: postgres:10-alpine
        networks:
            - nw-airflow
        ports:
            - 5432:5432
        restart: always
        tty: true
        volumes:
            - /home/ubuntu/airflow/db-data:/var/lib/postgresql/data
            - /home/ubuntu/airflow/postgres-initdb.d:/docker-entrypoint-initdb.d/

    airflow-scheduler:
        command: scheduler
        container_name: dc-airflow-scheduler
        depends_on:
            - postgres
        env_file:
            - airflow.env
        image: ghcr.io/grammy-jiang/airflow:latest
        networks:
            - nw-airflow
        restart: always
        tty: true
        volumes:
            - /home/ubuntu/airflow:/opt/airflow
    airflow-webserver:
        command: webserver
        container_name: dc-airflow-webserver
        depends_on:
            - postgres
            - airflow-scheduler
        env_file:
            - airflow.env
        image: ghcr.io/grammy-jiang/airflow:latest
        networks:
            - nw-airflow
        ports:
            - 8080:8080
        restart: always
        tty: true
        volumes:
            - /home/ubuntu/airflow:/opt/airflow

networks:
    nw-airflow:
        driver: bridge
